# config.yaml
data_path: "./dataset/ML1M/BPR_cv/"
train_file: "BPR_cv.train.inter"
vali_file: "BPR_cv.vali.inter"
test_file: "BPR_cv.test.inter"
side_info_path: "./dataset/ML1M/mv-tag-emb.npy"

entity_field: "mid"
target_field: "uid"
prior_type: 'noise'  # 'popularity' (인기 기반) 또는 'noise' (완전 무작위)
dims_mlp: [300, 300]
time_embedding_size: 16
dropout: 0.0

# Flow Matching 핵심 설정
n_step: 100        # [추가] 학습 시 시간 이산화 단계 (Training Steps)
inference_steps: 100  # 추론 시 ODE Solver 스텝 (Inference Steps)
eval_step: 10
# 학습 파라미터
head_drop_ratio: 0.0
batch_size: 1024
learning_rate: 0.001
epochs: 300
patience: 10         # [추가] 성능 향상이 없으면 조기 종료할 횟수